### ISSUE TITLE
For HacktoberFest

### ISSUE THREAD

**Issue by SamarthTMSL** [SamarthTMSL/samarthtmsl.github.io#33]
Here are few bugs and issues for making pull request:
1. Increase page speed.
2. Add more animation.
3. Fix the jitters and lags.
4. Change the loader to a better animated loader.
5. If you find any other bugs try to fix those.make any improvement you want.

**Comment by tejus0** [comment]
Hey @SamarthTMSL i can add more animations to your designer web app. I also felt that there are some places that can be made more awesome by animations like the cards that appear just below the get in touch at front. 
Similarly the loader can be more designer and good looking.  
So please assign me these issues.

**Comment by SamarthTMSL** [comment]
This repo already has the hacktoberfest tag so you can add more animations and make pr and it will count to hacktoberfest @tejus0

**Comment by tejus0** [comment]
> This repo already has the hacktoberfest tag so you can add more animations and make pr and it will count to hacktoberfest @tejus0 

So assign this issue to me.

**Comment by SamarthTMSL** [comment]
Create an issue and we will assign you @tejus0

**Comment by Apoorvakothari** [comment]
@SamarthTMSL I can increase the page speed. Can you assign me this?
