### ISSUE TITLE
Get in touch button gets turns blank when hovered on

### ISSUE THREAD

**Issue by jriyyya** [SamarthTMSL/samarthtmsl.github.io#35]
**The Issue**
The Get in touch button in the navbar turns completely blank momentarily once removing the mouse from it after a hover.

**Expected behavior**
The hover transition should be smooth and must not abruptly turn blank.

**Steps to recreate**
1) Go to the website
2) Scroll down till the navbar becomes sticky
3) Hover on the Get in touch button
4) Remove the mouse from top of it

**Screenshots**
![ScreenShot](https://user-images.githubusercontent.com/96080203/194375154-747c316b-6f8d-4d1f-81f6-c7165f5afa64.jpeg)

**Additional**
I believe I can fix this issue, please assign this to me under the hacktoberfest tag

**Comment by jriyyya** [comment]
Please assign this issue to me under hacktoberfest @SamarthTMSL

**Comment by SamarthTMSL** [comment]
Okay Sure

**Comment by SamarthTMSL** [comment]
@jriyyya  Assigned this issue with hacktoberfest tag.

**Comment by SamarthTMSL** [comment]
Merged Successfully @jriyyya
