### ISSUE TITLE
Improve UI of opened menu in mobile screens

### ISSUE THREAD

**Issue by vikrammahto** [SamarthTMSL/samarthtmsl.github.io#40]
Changing toggler icon is opened menu would improve UI. Also remove border on focus.
![Samarth-Empowering-the-Youth](https://user-images.githubusercontent.com/47027476/194524988-cd76d412-eee8-4ef0-ba68-0d3f9f6148cc.png)

**Comment by vikrammahto** [comment]
Please assign this issue to me.

**Comment by SamarthTMSL** [comment]
@vikrammahto Assinged
