### ISSUE TITLE
Card of guests section is inconsistent in size.

### ISSUE THREAD

**Issue by geekofshire** [SamarthTMSL/samarthtmsl.github.io#41]
![Screenshot from 2022-10-07 18-32-57](https://user-images.githubusercontent.com/82703398/194560536-ffeed362-b04a-45a8-9721-64ca3ed20969.png)
ADDITIONAL
Please assign me this issue as I can fix it. Do assign me under the hacktoberfest tag.

**Comment by SamarthTMSL** [comment]
Sure

**Comment by SamarthTMSL** [comment]
@geekofshire Assigned the issue with hacktoberfest tag.
