### ISSUE TITLE
UI of Guests card can be more functional

### ISSUE THREAD

**Issue by tejus0** [SamarthTMSL/samarthtmsl.github.io#45]
The UI of Guest card is somewhat bigger in size for mobile viewers. This the arrows created to slide the different guests can not be used effectively or very difficult to click on the arrow buttons due to their small size. 
The guests card can be made automatic slider with a time counter so that different guests can be shown on a particular time interval. 
So i request @SamarthTMSL to assign me this issue so that i can make your designer website more functional. 
![Screenshot_2022-10-08-16-25-31-955_com android chrome](https://user-images.githubusercontent.com/76488943/194704379-39f0c172-170b-4b80-be0d-5bb86797ef8b.jpg)

**Comment by SamarthTMSL** [comment]
@tejus0 Assinged

**Comment by tejus0** [comment]
Hey @SamarthTMSL I have made your Guests Card slider automatic so should I remove Arrows or the buttons below the slider ? Or is it fine ?

**Comment by SamarthTMSL** [comment]
Yes Sure make the loop infinite and buttons/arrows are not needed if the cards can me manually swiped also. Also please implement the same thing in our teams page and make a pr @tejus0

**Comment by tejus0** [comment]
Hey @SamarthTMSL I have made the sliders with infinite loops and removed arrows . But tell me about the teams page as it is not visible in your website . But when i open team.html my slider works fine . So i guess my changes have applied to teams page also . 
Additionally i have added red color to corners of each card which looks good .
So eview my changes in PR.

**Comment by SamarthTMSL** [comment]
We have reviewed the changes @tejus0

**Comment by tejus0** [comment]
Have you merged it under hacktoberfest label? As it is not reflecting in my progress.
