### ISSUE TITLE
Developments in footer

### ISSUE THREAD

**Issue by tejus0** [SamarthTMSL/samarthtmsl.github.io#46]
The design of footer is too raw. I have seen very good footers and I can make your footer beetee in design with every link in a mannered way. 
So please @SamarthTMSL assign me this issue of footer improvement. 
![Screenshot_2022-10-08-16-45-20-009-edit_com android chrome](https://user-images.githubusercontent.com/76488943/194704843-1068ef6e-8fff-4ca0-a10f-b56f2e1d07a9.jpg)

**Comment by SamarthTMSL** [comment]
@tejus0 Assigned

**Comment by tejus0** [comment]
Hey @SamarthTMSL  is the color combination right with you . I Have also added logo to your footer .
![image](https://user-images.githubusercontent.com/76488943/195675316-676c6c4d-fb1c-4f53-b8c2-1eca42b1762a.png)

**Comment by tejus0** [comment]
Hey @Sabyasachi-Seal why you closed the issue. I have made changes on the footer design and confirming about it from @SamarthTMSL . I have not committed the changes yet.

**Comment by tejus0** [comment]
Hey @Sabyasachi-Seal why you closed the issue. I have made changes on the footer design and confirming about it from @SamarthTMSL . I have not committed the changes yet.

**Comment by Sabyasachi-Seal** [comment]
@tejus0 Reopened . Just a reminder to merge latest branch into main before editing much

**Comment by tejus0** [comment]
@Sabyasachi-Seal  i am facing trouble in pushing my updates with main branch or with test branch. It is showing permission denied to me . "The requested URL returned error: 403"

**Comment by Sabyasachi-Seal** [comment]
try making pr from the online code editor

**Comment by tejus0** [comment]
> try making pr from the online code editor 

@Sabyasachi-Seal can you tell me how to do that.Are you talking about github code space. Please help me on this.

**Comment by Sabyasachi-Seal** [comment]
hey, after you have forked the repo, just go to the url and change from .com to .dev, it will open up the online code editor

**Comment by tejus0** [comment]
@Sabyasachi-Seal  created pull request , Please check .
