### ISSUE TITLE
Want to add DarkTheme feature on all Pages

### ISSUE THREAD

**Issue by yasaswini999** [SamarthTMSL/samarthtmsl.github.io#47]
@SamarthTMSL  pls assign this ticket so that i wont loose the count on it
Thank you:)

**Comment by SamarthTMSL** [comment]
@yasaswini999 Assigned

**Comment by KaxitPandya** [comment]
@SamarthTMSL  Please assign it to me I shall make it compatible in dark mode as well

**Comment by SamarthTMSL** [comment]
@KaxitPandya Done
