### ISSUE TITLE
fix get in touch btn

### ISSUE THREAD

**Issue by vivianemartini** [SamarthTMSL/samarthtmsl.github.io#52]
Hi there, right now the button on the banner is now working properly, is no showind the hover and is not clickable. 
pls assign this ticket so that i wont loose the count on it
Thank you:)

**Comment by SamarthTMSL** [comment]
Please refer with a screenshot

**Comment by vivianemartini** [comment]
[showing hover issue](https://vimeo.com/758919729/a285b0f16a)

**Comment by SamarthTMSL** [comment]
But it is working correctly

**Comment by Hiresh23** [comment]
i would like to contribute to issue ,please assign

**Comment by Hiresh23** [comment]
can you please assign it with hacktoberfest tag

**Comment by vivianemartini** [comment]
hey @SamarthTMSL, I made a new [video](https://vimeo.com/759220460/9cc6ca7746), when I inspected the hover was appering, so the hover and clickable behaviour should be visible only when the browser is resized? 

Cause if that's the case I would suggest to remove the button from the hero banner because it gives the user the idea of been clickable, this would improve the website user experience.

if this is the case, I"d like to work on that for hacktoberfest

**Comment by SamarthTMSL** [comment]
![Screenshot (24)](https://user-images.githubusercontent.com/103263000/195167888-0df02cbd-9a33-4d5b-8002-117e11028c52.png)

We checked again found that the button is not working in some scenarios because the section underneath that is overlapping with the button. We want the button to be there. Can you fix that @vivianemartini @Hiresh23 ?

**Comment by vivianemartini** [comment]
yes I can, can you assign to me?

**Comment by Meghadri-Koley** [comment]
@vivianemartini Assigned

**Comment by vivianemartini** [comment]
Hi @Meghadri-Koley, I've submited my PR, in case of acceptance, could you add the label for hacktoberfest-accepted into the issue? 
have a good one

**Comment by Sabyasachi-Seal** [comment]
Tag Added and PR Merged .
