### ISSUE TITLE
Fix "Get in Touch" Button

### ISSUE THREAD

**Issue by SamarthTMSL** [SamarthTMSL/samarthtmsl.github.io#69]
Fix This Button in all pages.

![image](https://user-images.githubusercontent.com/103263000/196609794-e8059688-1974-432e-bded-8799d5a84aa8.png)

**Comment by najeebkp** [comment]
Hi @SamarthTMSL  please assign me this

**Comment by vaibhv232** [comment]
assign me this task

**Comment by SamarthTMSL** [comment]
Sorry for the delay, but since @najeebkp asked for the issue first, we will assign it to him.
